version: '3.1'
services:
  web:
    image: odoo:15.0
    container_name: odoo-server
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
      - "8071:8071"
    volumes:
      - ./odoo-web-data:/var/lib/odoo-web
      - ./config:/etc/odoo
      - ./addons/:/mnt/extra-addons/
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    networks:
      internal:
        ipv4_address: 172.0.0.2
  db:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    networks:
      internal:
        ipv4_address: 172.0.0.3
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: ./secrets/odoo_pg_pass

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/24
